name: flutter_wanandroid
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # toast
  fluttertoast: ^4.0.1
  # 网络库 https://github.com/flutterchina/dio
  dio: ^4.0.0
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.25.0
  # 状态管理 https://github.com/rrousselGit/provider
  provider: ^5.0.0
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.0.0
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^0.3.3
  # 获取当前设备信息 https://github.com/flutter/plugins/tree/master/packages/device_info
  device_info: 2.0.0
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^2.5.1
  # html https://pub.flutter-io.cn/packages/html
  html: ^0.15.0
  # cookie https://github.com/flutterchina/cookie_jar
  cookie_jar: 3.0.1
  # cookie管理 https://github.com/flutterchina/dio/tree/master/plugins/cookie_manager
  dio_cookie_manager: ^2.0.0
  # 查找文件系统路径 https://pub.dev/packages/path_provider
  path_provider: 2.0.1
  # 消息传递 EventBus https://pub.dev/packages/event_bus
  event_bus: ^2.0.0
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^2.0.3
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: 2.0.2
  # 分享 https://github.com/flutter/plugins/tree/master/packages/share
  share: ^0.6.1+1
  # 轮播图 https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6
  # 列表悬浮头 https://github.com/fluttercommunity/flutter_sticky_headers
  sticky_headers: ^0.2.0
  # 数据库 https://pub.flutter-io.cn/packages/floor_generator
  floor: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # 数据库
  floor_generator: ^1.0.0
  build_runner: ^1.7.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
